version: '3.9'

services:
  db:
    image: postgres:16.0-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-root}
      - POSTGRES_DB={POSTGRES_DB:-postgres}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - db:${PGDATA:-/var/lib/postgresql/data}
volumes:
  db: